### PR TITLE
somehow forgot to receive object

### LINKED ISSUE #67: Invalid arguments in ReadByQueryEqualToValue
Getting mismatched arguments when compiling:

```
Compiling syntax tree
Firebase.Database/JS.uno(88.24): E2009: Call to 'Firebase.Database.ReadByQueryEqualToValue(string,string,string)' has some invalid arguments (string,string,Java.Object)
/Users/caseywilliams/Fuse/QuickLaps/Firebase.Database/JS.uno(88,25): Error E2009: Call to 'Firebase.Database.ReadByQueryEqualToValue(string,string,string)' has some invalid arguments (string,string,Java.Object)
```

Database.uno:
```
[Foreign(Language.Java)]
        public ReadByQueryEqualToValue(string path, string key, string val)
        @{
            ValueEventListener dataListener = new ValueEventListener() {
                @Override
                public void onDataChange(DataSnapshot dataSnapshot)
                {
                    Object snapshotValue = dataSnapshot.getValue();
                    @{ReadByQueryEqualToValue:Of(_this).Resolve(string):Call((
                        (snapshotValue == null)
                            ? null
                            : (snapshotValue instanceof Map)
                                ? new JSONObject((Map) snapshotValue).toString()
                                : (snapshotValue instanceof List)
                                    ? new JSONArray((List) snapshotValue).toString()
                                    : (snapshotValue instanceof String)
                                        ? "\"" + snapshotValue.toString() + "\""
                                        : snapshotValue.toString()
                    ))};
                }

                @Override
                public void onCancelled(DatabaseError databaseError)
                {
                    @{ReadByQueryEqualToValue:Of(_this).Reject(string):Call(databaseError.toString())};
                }
            };
            DatabaseReference ref = (DatabaseReference)@{DatabaseService._handle:Get()};
            ref.child(path).orderByChild(key).equalTo(val).addListenerForSingleValueEvent(dataListener);
        @}
```

JS.uno:
```
var path = args[0].ToString();
            var key = args[1].ToString();
            var val = args[2];

            if defined(iOS)
            {
                return new ReadByQueryEqualToValue(
                    path, key,
                    JSON.ObjCObject.FromJSON(JSON.ScriptingValue.ToJSON(val))
                );
            }
            else if defined(Android)
            {
                return new ReadByQueryEqualToValue(
                    path, key,
                    JSON.JavaObject.FromJSON(JSON.ScriptingValue.ToJSON(val))
                );
            }
```

### PR DESCRIPTION
**Pull request by LuisRodriguezLD**
fixes  #67 
probably a merge error, not sure but it should work now.

### CODE REVIEW

**Comment by shnupta** [comment]
This doesn't fix on my machine as else where in the code `(String) val` causes an error where `UnoObject` cannot be cast to a string

**Comment by LuisRodriguezLD** [comment]
interesting, it _should_ work. mind if I see a log? please

**Comment by shnupta** [comment]
Here's what I had when building an Android preview:
```
/Users/caseywilliams/Fuse/QuickLaps/build/Android/Preview/app/src/main/java/com/foreign/Firebase/Database/ReadByQueryEqualToValue.java:63: error: incompatible types: UnoObject cannot be converted to String
        if(val instanceof String){
           ^
/Users/caseywilliams/Fuse/QuickLaps/build/Android/Preview/app/src/main/java/com/foreign/Firebase/Database/ReadByQueryEqualToValue.java:64: error: incompatible types: UnoObject cannot be converted to String
            String obj = (String) val;
                                  ^
/Users/caseywilliams/Fuse/QuickLaps/build/Android/Preview/app/src/main/java/com/foreign/Firebase/Database/ReadByQueryEqualToValue.java:66: error: incompatible types: UnoObject cannot be converted to Double
        } else if (val instanceof Double){
                   ^
/Users/caseywilliams/Fuse/QuickLaps/build/Android/Preview/app/src/main/java/com/foreign/Firebase/Database/ReadByQueryEqualToValue.java:67: error: incompatible types: UnoObject cannot be converted to Double
            Double obj = (Double) val;
                                  ^
/Users/caseywilliams/Fuse/QuickLaps/build/Android/Preview/app/src/main/java/com/foreign/Firebase/Database/ReadByQueryEqualToValue.java:69: error: incompatible types: UnoObject cannot be converted to Boolean
        } else if( val instanceof Boolean  ){
                   ^
/Users/caseywilliams/Fuse/QuickLaps/build/Android/Preview/app/src/main/java/com/foreign/Firebase/Database/ReadByQueryEqualToValue.java:70: error: incompatible types: UnoObject cannot be converted to Boolean
            Boolean obj = (Boolean) val;
```

**Comment by LuisRodriguezLD** [comment]
mm, I still don't see it. are you on a PC by any chance?

**Comment by LuisRodriguezLD** [comment]
Still can't see it on my Mac. Even made a small example, give it a try and let me know if you find anything.

**Comment by shnupta** [comment]
I'm on mac too, I'll make a copy of my project and pull your version and test again. I don't think I made any changes to Database.uno that would have caused it but I'll let you know

**Comment by shnupta** [comment]
Tested on both Mac and PC, works perfectly!:)

**Comment by LuisRodriguezLD** [comment]
great! ready to merge @cbaggers 👍

**Comment by ecstipan** [comment]
Still having the same issue as #67 on iOS and Android build on the most-current branch.

`Compiling syntax tree
/Users/ecstipan/Dropbox/BLINK FUSE/BLINK/Fuse.Firebase/src/Firebase.Database/JS.uno(81.24): E2009: Call to 'Firebase.Database.ReadByQueryEqualToValue(string,string,string)' has some invalid arguments (string,string,ObjC.Object)
/Users/ecstipan/Dropbox/BLINK FUSE/BLINK/Fuse.Firebase/src/Firebase.Database/JS.uno(81,25): Error E2009: Call to 'Firebase.Database.ReadByQueryEqualToValue(string,string,string)' has some invalid arguments (string,string,ObjC.Object)`

**Comment by LuisRodriguezLD** [comment]
@ecstipan correct, this _must_ be merged before master works again

**Comment by LuisRodriguezLD** [comment]
Will now merge this, please reopen if an issue comes up

**Pull request merged**
